my_string = input('Авто подчет символов, введите ваше слово: ')
print('Кол-во символов:',my_string.__len__())
print('Строка в верхнем регистре:',my_string.upper())
print('Строка в нижнем регистре:',my_string.lower())
print('Строка без пробелов:',my_string.replace(' ', ''))
print('Первый символ:',my_string[0])
print('Последний символ:',my_string[-1])